export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const LOAD_TEACHER_PROFILE = 'LOAD_TEACHER_PROFILE';
export const LOAD_TEACHER_PROFILE_FAIL = 'LOAD_TEACHER_PROFILE_FAIL';

export const LOAD_STUDENT = 'LOAD_STUDENT';
export const LOAD_STUDENT_FAIL = 'LOAD_STUDENT_FAIL';

export const ADD_STUDENT = 'ADD_STUDENT';
export const ADD_STUDENT_FAIL = 'ADD_STUDENT_FAIL';

export const REMOVE_STUDENT = 'REMOVE_STUDENT';
export const REMOVE_STUDENT_FAIL = 'REMOVE_STUDENT_FAIL';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const CLEAR_TEACHER_PROFILE = 'CLEAR_TEACHER_PROFILE';

export const CLEAR_STUDENT_PROFILE = 'CLEAR_STUDENT_PROFILE';

export const LOAD_ACTIVITIES = 'LOAD_ACTIVITIES';
export const LOAD_ACTIVITIES_FAIL = 'LOAD_ACTIVITIES_FAIL';
export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const ADD_ACTIVITY_FAIL = 'ADD_ACTIVITY_FAIL';
export const REMOVE_ACTIVITY = 'REMOVE_ACTIVITY';
export const REMOVE_ACTIVITY_FAIL = 'REMOVE_ACTIVITY_FAIL';

export const SEND_ACTIVITIE = 'SEND_ACTIVITIE';
export const SEND_ACTIVITIE_FAIL = 'SEND_ACTIVITIE_FAIL';

export const ADD_MARK = 'ADD_MARK';
export const ADD_MARK_FAIL = 'ADD_MARK_FAIL';
